// Set RawCsvPath to your downloaded CSV. Transformation logic from the original workbook.
let
  RawCsvPath = "C:/data/entsoe_data_2024_2025.csv",
  Origine = Csv.Document(File.Contents(RawCsvPath), [Delimiter = ",", Columns = 39, Encoding = 65001]),
  #"Intestazioni alzate di livello" = Table.PromoteHeaders(Origine, [PromoteAllScalars = true]),
  #"Modificato tipo di colonna con impostazioni locali" = Table.TransformColumnTypes(#"Intestazioni alzate di livello", {{"price", type number}, {"nuclear", type number}, {"fossil_gas", type number}, {"solar", type number}, {"waste", type number}, {"wind_offshore", type number}, {"wind_onshore", type number}, {"_biomass_actual_aggregated_", type number}, {"_fossil_brown_coal_lignite_actual_aggregated_", type number}, {"_fossil_coal_derived_gas_actual_aggregated_", type number}, {"_fossil_gas_actual_aggregated_", type number}, {"_fossil_hard_coal_actual_aggregated_", type number}, {"_fossil_oil_actual_aggregated_", type number}, {"_hydro_pumped_storage_actual_aggregated_", type number}, {"_hydro_pumped_storage_actual_consumption_", type number}, {"_hydro_run_of_river_and_poundage_actual_aggregated_", type number}, {"_hydro_water_reservoir_actual_aggregated_", type number}, {"_other_actual_aggregated_", type number}, {"_other_renewable_actual_aggregated_", type number}, {"_solar_actual_aggregated_", type number}, {"_wind_onshore_actual_aggregated_", type number}, {"biomass", type number}, {"energy_storage", type number}, {"fossil_brown_coal_lignite", type number}, {"fossil_coal_derived_gas", type number}, {"fossil_hard_coal", type number}, {"fossil_oil", type number}, {"fossil_oil_shale", type number}, {"fossil_peat", type number}, {"geothermal", type number}, {"hydro_pumped_storage", type number}, {"hydro_run_of_river_and_poundage", type number}, {"hydro_total", type number}, {"hydro_water_reservoir", type number}, {"marine", type number}, {"other", type number}, {"other_renewable", type number}, {"datetime", type datetimezone}, {"country", type text}}, "en-US")
in
  #"Modificato tipo di colonna con impostazioni locali"
