-- Export this result set as a UTF-8 CSV with headers.
-- The timestamp format matches the existing Power BI/Excel input export.
SELECT strftime('%d/%m/%Y %H:%M', datetime_utc) AS datetime_utc,
       "country",
       "price",
       "nuclear",
       "fossil_gas",
       "solar",
       "waste",
       "wind_offshore",
       "wind_onshore",
       "_biomass_actual_aggregated_",
       "_fossil_brown_coal_lignite_actual_aggregated_",
       "_fossil_coal_derived_gas_actual_aggregated_",
       "_fossil_gas_actual_aggregated_",
       "_fossil_hard_coal_actual_aggregated_",
       "_fossil_oil_actual_aggregated_",
       "_hydro_pumped_storage_actual_aggregated_",
       "_hydro_pumped_storage_actual_consumption_",
       "_hydro_run_of_river_and_poundage_actual_aggregated_",
       "_hydro_water_reservoir_actual_aggregated_",
       "_other_actual_aggregated_",
       "_other_renewable_actual_aggregated_",
       "_solar_actual_aggregated_",
       "_wind_onshore_actual_aggregated_",
       "biomass",
       "energy_storage",
       "fossil_brown_coal_lignite",
       "fossil_coal_derived_gas",
       "fossil_hard_coal",
       "fossil_oil",
       "fossil_oil_shale",
       "fossil_peat",
       "geothermal",
       "hydro_pumped_storage",
       "hydro_run_of_river_and_poundage",
       "hydro_total",
       "hydro_water_reservoir",
       "other",
       "other_renewable"
FROM electricity_price_analysis;
